### PR TITLE
Fix the issue that checks for new input fields constantly

### PR DESCRIPTION
**Pull request by rogiermuijen**

### CODE REVIEW

**Comment by rogiermuijen** [comment]
Hi @limpkin , I disabled an issue that checks for new input fields constantly in order to avoid causing a lot of usage of CPU and RAM, and instead of it, I implemented MutationObserver to check new input fields whenever DOM is changed.
If you have any chance to look at this, please check it.
And I think we need to refactor this extension to optimize it.
What do you think?
Thanks

**Comment by rogiermuijen** [comment]
PS: this PR was just implemented on the build version of the project itself to check if it can improve the performance. So I am going to implement it on the main project after review it.

**Comment by limpkin** [comment]
wow, thanks a lot for that!  
Were you able to check the feature on chrome / ff / safari?
More importantly, have you checked for high resource usage on ajax websites? I'm not the main developer but I'm wondering if your MutationObserver is called once for each change on the page... which could lead to high resource usage if the website is constantly changing.

**Comment by rogiermuijen** [comment]
I checked it only on Chrome, but I think it should work on Firefox and Safari also.
Regarding the ajax websites, could you please let me know the sample ajax website URLs so I can check this feature on those platforms and fix it.
And from tomorrow, I am going to work on ensuring that each change on the page won't lead to high resource usage if the website is constantly changing.
Thanks

**Comment by rogiermuijen** [comment]
I see, will test it on those platforms.

**Comment by rogiermuijen** [comment]
Hi @limpkin , I fixed a lot of CPU usage issue and tested it on Chrome, Firefox, and Safari.
Could you please check it? Thanks

**Comment by limpkin** [comment]
Excellent work!
Could you explain what was happening in details?
I'm afraid I'm already on holidays for 2 weeks. Could you make a .zip using
the updatecleanversion.sh script and put it in this issue so that issue
observers may try it and confirm that it's solved?

**Comment by rogiermuijen** [comment]
I tried to find the issue on this link http://www.clubpatrimoine.com/home.aspx.
It was causing a lot of CPU usage, for this reason, the above page was frozen.
So I debugged it deeply and finally noticed that this issue was caused because some functions which take a lot of CPU usage were called repeatedly.
```javascript
mcCombs.gotSettings(req.data);
```
So I made this extension ensure that those functions are called only once. After I fix this issue, the CPU usage was reduced remarkably and the above page was not frozen also.

**Comment by limpkin** [comment]
Nice! Do you know why this was called so often? In which cases is the get
settings is received?

**Comment by rogiermuijen** [comment]
`get_settings` action is triggered by the `mcCombs.init` function:
```javascript
/*
* Init the mcCombinations procedure.
* This should be called just once per body/frame!
*/
mcCombinations.prototype.init = function (callback) {
    if (this.settings.debugLevel > 4) cipDebug.log('%c mcCombinations: %c Init', 'background-color: #c3c6b4', 'color: #333333');

    this.callback = callback;
    messaging({ "action": "get_settings" });
};
```
And as you can see above function, this action shoud be called only once, but it was called repeatedly. And based on my code review, the `mcCombs.init` function is called by the `content_script_loaded` action and all the queued functions should be called only once.
But the `content_script_loaded` action was also called repeatedly.
It seems like there are still some unclear issues that I didn't manage, so I'd like to work on it.
But I think we are on the right way to track the issue so I am sure this issue will be surely fixed.
I'd like to give the reviewers testable extension after I fixed this issue and everything is clear. I don't want our extension to get a bad reputation from our users.
I will keep working on it this weekend and possibly will give it to the reviewers on Sunday.
Is that ok with you?

**Comment by limpkin** [comment]
Isn't contentscriptsloaded called repeatedly because of constant page
refreshes due to the ajax content?

**Comment by rogiermuijen** [comment]
Btw I can't find the code part that implements the refreshes due to the ajax content.
Could you please let me know where the code part is placed in if you know it?
Thanks

**Comment by rogiermuijen** [comment]
I see, let me check it myself then. Btw, currently, our contract was paused because of me.
I was having trouble with my Upwork account. I am very confused about this.
Could you please restart our contract so I can continue working from today?
Thanks and sorry for bothering you.

**Comment by rogiermuijen** [comment]
Hi, I gave testers the current version of extension as .zip file.
Let's wait for their feedback, meanwhile I'd like to work on another task or do you want me to keep working on the current task?

**Comment by limpkin** [comment]
It seems I'm not being clear: this is not considered as solved until the
root cause is found.
Please pause any work before I'm back from holidays

**Comment by rogiermuijen** [comment]
I see, will get back to you with the fixed version within a few days.
Thanks

**Comment by limpkin** [comment]
Again, before getting to a fixed version I'd like to know the root cause of
the problem.
No need for code, I just need an explanation so we are sure in the future
that this won't happen again.

**Comment by rogiermuijen** [comment]
Yes, it does make sense what you mean for solving this problem.
My thoughts so far for the root cause of this problem are
- checking for new input field constantly every 100ms
- not implementing the mooltipass event chain correctly and clearly(didn't check it in fully yet)
- not destructing any pre-used objects(something like event listeners) and variables correctly - it may cause unexpected problems

Anyway, I will try to figure out what is the root cause of this problem exactly.

**Comment by limpkin** [comment]
> not implementing the mooltipass event chain correctly and clearly(didn't
check it in fully yet)

This is like saying "the program is not working like it should / was
designed to". This sentence couldn't be more generic....


> not destructing any pre-used objects(something like event listeners) and
variables correctly - it may cause unexpected problems

This is the thing: why should they be destructed in the first place? We
have identified that the problem lies in the content script, which is
destroyed (in theory) at each page refresh.


In the future please refrain from making this kind of generic statement
without providing source code lines, function names, source file names, or
diagrams.

**Comment by rogiermuijen** [comment]
Hi Mathieu, hope you are having good holidays.
I have worked on debugging the CPU usage issue so far, and finally figured out why was the issue caused when the Patrimonie page was loaded.
So this issue was caused in the `mcCombinations.detectSubmitButton` function.
Please have a look at the below code
```javascript
/*
 * Detect submit button for the given field and container.
 *
 * @param field {jQuery object}
 * @param container {jQuery object}
 * @return submitButton {DOM node} or undefined
 */
mcCombinations.prototype.detectSubmitButton = function detectSubmitButton(field, container, isSubmitButtonPreviouslyDetected) {
    ...
    for (var selectorIndex = 0; selectorIndex < BUTTON_SELECTORS.length; selectorIndex++) {
        ...
    }
    // If we haven't detected submit button yet, try to find it in parent container.
    if (container[0] != mpJQ('body')[0]) {
        return this.detectSubmitButton(field, container.parent(), isSubmitButtonPreviouslyDetected)
    }
}
```

Please focus on the following code part

```javascript
    // If we haven't detected submit button yet, try to find it in parent container.
    if (container[0] != mpJQ('body')[0]) {
        return this.detectSubmitButton(field, container.parent(), isSubmitButtonPreviouslyDetected)
    }
```
As you can see, if this function hasn't detected the submit button, it tries to find it in parent container - this is the problem.
So in this way, this function will be called continuously until it detects the submit button or the container is the root DOM element(in this case the root DOM element is body tag).
So I counted how many times this function is called repeatedly, and this function was called 25 times.
For this reason, it caused a lot of CPU usage issue.

**Solution**
In reality, we don't need to find the submit button until container will be the root element if it didn't detect the submit button, I think.
So we can solve this issue by limiting the repeated count, maybe limit to 10?
What do you think?
Also, I tested it with this limited count, and it works fine.

**Comment by rogiermuijen** [comment]
Hi Mathieu, hope you had a good holiday.
Could you please let me know if I can push my working result for the issue I mentioned above?
Thanks

**Pull request closed without merging**
